version: '3.1'

services:
  nodejs:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: slider:latest
    container_name: slider
    volumes:
      - .:/app
    ports:
      - '7777:7777'
